# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Campus.create!(code: 1, name: "St. George")
Campus.create!(code: 3, name: "Scarbourough")
Campus.create!(code: 5, name: "Mississauga")

Instructor.create!(name: "Gary Baumgartner")
Instructor.create!(name: "Tom Fairgrieve")
Instructor.create!(name: "Paul Gries")
Instructor.create!(name: "Radford Neal")
Instructor.create!(name: "Bogdan Simion")
Instructor.create!(name: "Danny Heap")
Instructor.create!(name: "Jacqueline Smith")
Instructor.create!(name: "David Liu")
Instructor.create!(name: "Toniann Pitassi")
Instructor.create!(name: "Karen Reid")
Instructor.create!(name: "Faith Ellen",)
Instructor.create!(name: "Sajad Shirali-Shahreza")
Instructor.create!(name: "Steve Engels")
Instructor.create!(name: "Francois Pitt")
Instructor.create!(name: "Sam Toueg")
Instructor.create!(name: "Sasa Milic")
Instructor.create!(name: "Lindsey Shorser")
Instructor.create!(name: "Joey Freund")
Instructor.create!(name: "Mat Zeleski")
Instructor.create!(name: "Amir Chinaei")
Instructor.create!(name: "Velian Pandeliev")
Instructor.create!(name: "Kyros Kutulakos")
Instructor.create!(name: "Roger Grosse")
Instructor.create!(name: "Christina Christara")
Instructor.create!(name: "Diane Horton")
Instructor.create!(name: "Peter Marbach")
Instructor.create!(name: "Allan Jepson")
Instructor.create!(name: "Sheila McIlraith")
Instructor.create!(name: "Frank Rudzicz")
Instructor.create!(name: "Michael Guerzhoy")
Instructor.create!(name: "David Duvenaud")
Instructor.create!(name: "David Levin")
Instructor.create!(name: "Edy Garfinkiel")
Instructor.create!(name: "David Holman")
Instructor.create!(name: "Marina Barsky")
Instructor.create!(name: "Ken Jackson")
Instructor.create!(name: "Mario Grech")
Instructor.create!(name: "Steve Cook")
Instructor.create!(name: "Aleksandar Nikolov")
Instructor.create!(name: "Steven Shapiro")
Instructor.create!(name: "Helen Kontozopoulos")
Instructor.create!(name: "Narges Norouzi")
